### ISSUE TITLE
Change JavaScript plugin repository URL

### ISSUE THREAD

**Issue by kaustavdm** [getgauge/getgauge.github.io#14]
Should be https://github.com/getgauge-contrib/gauge-js.

**Comment by kashishm** [comment]
Fixed via 4ffd1b374b7154440e08f2ba39f488596093a3cf

**Comment by mahendrakariya** [comment]
@kashishm Shouldn't this change be done in the [plugin_data.yaml](https://github.com/getgauge/getgauge.github.io/blob/redesign/data/plugin_data.yaml) file in the redesign branch?

**Comment by kashishm** [comment]
I have done it there also 59e413dfc8fee1288eece87d645aa493a184cad7

**Comment by mahendrakariya** [comment]
Coool!
