### ISSUE TITLE
"Why Gauge is better for" dropdown seems broken in Firefox

### ISSUE THREAD

**Issue by RPrimrose** [getgauge/getgauge.github.io#16]
On the landing page, if I'm in Firefox and click the word "testers" in "Why Gauge is better for Testers" then the expected dropdown isn't shown. 

Checking the console shows the following error each time I click the word "testers"

```
ReferenceError: event is not defined
<anonymous> application.js:2
ie.event.dispatch()  jquery-1.11.2.js:25
ie.event.add/g.handle() jquery-1.11.2.js:24
```

(Everything works fine for me in Chrome/IE)

**Comment by apoorvam** [comment]
This issue is now fixed. Check out [getgauge.io](http://getgauge.io)
