### ISSUE TITLE
Add icons for supported languages and platforms

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/getgauge.github.io#2]

**Comment by sriv** [comment]
Icons for platforms have been added. Do you think we need icons for languages/platforms in the [plugins page](http://getgauge.io/plugins/index.html)

**Comment by prateekbaheti** [comment]
@sriv Don't think its needed as the full names are mentioned on the plugins page. I think a lack of plugins page was the cause of the issue in the earlier website design.
Closing this issue.
